# Generated by Django 3.1.7 on 2021-03-26 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Regione',
            fields=[
                ('codice_regione', models.IntegerField(primary_key=True, serialize=False, verbose_name='codice Istat')),
                ('nome', models.CharField(db_index=True, max_length=300, verbose_name='nome')),
            ],
            options={
                'verbose_name': 'regione',
                'verbose_name_plural': 'regioni',
                'ordering': ['nome'],
            },
        ),
    ]
