# Generated by Django 3.1.7 on 2021-03-27 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comuni', '0002_provincia'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiornalieroProvincia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
