# Generated by Django 3.1.7 on 2021-03-28 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comuni', '0003_giornalieroprovincia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GiornalieroProvincia',
        ),
    ]
